"""empty message

Revision ID: 2e24741f553d
Revises: f16675216f18
Create Date: 2021-05-20 16:10:51.403253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e24741f553d'
down_revision = 'f16675216f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categorie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('canton', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories.id'], name='vendor_categorie_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='vendor_service_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='vendor_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vendor_pkey')
    )
    # ### end Alembic commands ###
