"""empty message

Revision ID: 7c5ed2860099
Revises: 2e24741f553d
Create Date: 2021-05-21 00:59:41.776820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5ed2860099'
down_revision = '2e24741f553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('services_categorie_id_fkey', 'services', type_='foreignkey')
    op.drop_column('services', 'categorie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('categorie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('services_categorie_id_fkey', 'services', 'categories', ['categorie_id'], ['id'])
    # ### end Alembic commands ###
